# frontend-resources.yaml

# --- Namespace (Assumes 'app-services' already exists) ---

# --- Deployment for the Frontend ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: app-services
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        # This image now contains Nginx + static build
        image: moonsol124/crud-dashboard-frontend:latest
        imagePullPolicy: Always
        ports:
        # Nginx listens on port 80
        - containerPort: 80
        # Runtime Env Vars usually not needed if VITE_ vars baked into build
---
# --- Service for Frontend ---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: app-services
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80       # Service listens on port 80 internally
    targetPort: 80 # Forwards traffic to Nginx container on port 80
  # --- DECISION POINT ---
  # Use ClusterIP if accessing ONLY via Ingress
  # Use NodePort if you want to test DIRECTLY via Minikube IP + NodePort *before* setting up/testing Ingress
  type: ClusterIP # <<< RECOMMENDED for use with Ingress
  # type: NodePort   # Use this line INSTEAD if you want to test directly first via 'minikube service frontend-svc --url'