apiVersion: v1
kind: Service
metadata:
  name: crud-dashboard-service
spec:
  selector:
    app: crud-dashboard
  ports:
  - protocol: TCP
    port: 80  # Service port (internal to the cluster)
    targetPort: 5173 # Container port
  type: NodePort
