# .github/workflows/deploy-gh-pages.yml
name: Deploy Frontend to GitHub Pages

# Run workflow on pushes to the main branch that change frontend files
on:
  push:
    branches: [ main ]
    paths: # Optional but recommended: only run if frontend code changes
      - 'src/**'
      - 'public/**'
      - 'index.html'
      - 'package.json'
      - 'package-lock.json'
      - 'vite.config.js'
      - 'tailwind.config.js' # Add other relevant config files
      - 'postcss.config.js'
      - '.github/workflows/deploy-gh-pages.yml' # Trigger if workflow changes
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Use the same Node version as your Dockerfile/dev env
          cache: 'npm' # Cache npm dependencies

      - name: Install Dependencies
        run: npm ci # Use ci for clean installs

      - name: Build Static Assets
        # This uses the 'base' path configured in vite.config.js
        run: npm run build
        env: # <<< ADDING/MODIFYING THE ENV BLOCK HERE
          NODE_ENV: production # Keep this as recommended
          # Inject your VITE_ variables with their production values
          VITE_API_GATEWAY_URL: http://34.31.33.116:80
          VITE_OAUTH_SERVER_URL: http://34.68.64.43:80
          VITE_OAUTH_CLIENT_ID: a41825cf-211a-4dd9-9bd7-cd3d95850fd0
          # *** IMPORTANT: Use the GitHub Pages Redirect URI here! ***
          # This MUST match the redirect URI registered on your OAuth server
          # for your GitHub Pages client ID, and it must match what your HashRouter expects.
          VITE_OAUTH_REDIRECT_URI: http://34.31.33.116/auth/callback


      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path to the directory containing build output (default 'dist' for Vite)
          path: './dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # This action uses the artifact uploaded in the previous step
        # and deploys to the gh-pages environment automatically