# .github/workflows/docker-publish-frontend.yml
name: Build and Push Docker Image (Frontend)

on:
  push:
    branches: [ main ]
    paths: # Optional: Trigger only if frontend files change
      - 'crud-dashboard/**' # Adjust path if your frontend is elsewhere
      - '.github/workflows/docker-publish-frontend.yml'
  workflow_dispatch:

jobs:
  build-and-push-frontend: # Changed job name
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Use the same secret
          password: ${{ secrets.DOCKERHUB_TOKEN }}   # Use the same secret

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          # Set context to the frontend directory
          context: . # Adjust path if needed
          file: ./Dockerfile # Path to Dockerfile relative to repo root
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/crud-dashboard-frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/crud-dashboard-frontend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Optional: Pass build arguments for VITE_ variables if defined in Dockerfile
          # build-args: |
          #   VITE_API_GATEWAY_URL=${{ secrets.VITE_API_GATEWAY_URL }} # Use secrets or vars if needed
          #   VITE_OAUTH_CLIENT_ID=${{ secrets.VITE_OAUTH_CLIENT_ID }}
          #   VITE_OAUTH_REDIRECT_URI=${{ secrets.VITE_OAUTH_REDIRECT_URI }}